### PR TITLE
[JENKINS-36946] - Add hint for disabling empty ownership summaries

### PR DESCRIPTION
**Pull request by oleg-nenashev**
https://issues.jenkins-ci.org/browse/JENKINS-36946

screen shot 2016-07-26 at 12 01 38

CC @KostyaSha who requested it at some point

### CODE REVIEW

**Comment by KostyaSha** [comment]
Could you make screenshot?

**Comment by oleg-nenashev** [comment]
@KostyaSha Added it to the PR summary

**Comment by oleg-nenashev** [comment]
oh, discovered a typo

**Comment by KostyaSha** [comment]
@oleg-nenashev maybe replace this text with some icon? My concern was also about this ugly table.

**Comment by oleg-nenashev** [comment]
Yeah, it's ugly. I'll see what I can do

**Comment by oleg-nenashev** [comment]
I'll do it as a separate PR

**Pull request merged**
