### PR TITLE
Add ability to collapse the Folder Owners box on folder and node pages.

### PR DESCRIPTION
**Pull request by refortin**
The Folder Owners box can be large on folders with many secondary owners obscuring the folder content.  The changes are a proposal to make the box collapsible. Click the folder header to open and close the box.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Test failure is unrelated, my fault: https://github.com/jenkins-infra/pipeline-library/pull/37

**Comment by oleg-nenashev** [comment]
And yes, the code itself looks good to me, just need to do some manual testing

**Comment by refortin** [comment]
Three images showing the original Folder Owners view, the closed view and the open view.

Original View
folder-orignal

Closed View
folder-closed

Open View
folder-open

**Comment by oleg-nenashev** [comment]
I somehow forgot about this PR. Time to finally release it, I'd guess

**Comment by icereed** [comment]
hi @oleg-nenashev , thanks for merging? Could you also release the new version since we are not able to use this plugin otherwise. We are looking very forward to using this new feature.

**Comment by KalleOlaviNiemitalo** [comment]
Too bad that Internet Explorer does not support [\<details\>](<https://developer.mozilla.org/docs/Web/HTML/Element/details> "<details>: The Details disclosure element - HTML: HyperText Markup Language | MDN").

**Pull request merged**
