### PR TITLE
JENKINS-62589 Compatibility with tables to divs

### PR DESCRIPTION
**Pull request by timja**
https://issues.jenkins-ci.org/browse/JENKINS-62589

A number of tests don't pass due to JENKINS-48885 thoughts? I've ignored them for now as that would be the most straightforward way, otherwise I think this plugin needs migrating to not extend Plugin and use initialisers, etc.

@oleg-nenashev 

note: this might require https://github.com/jenkinsci/matrix-auth-plugin/pull/83 as well

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Yes, `getPlugin()` in tests is a major issue. This is why I was trying to fix https://issues.jenkins-ci.org/browse/JENKINS-48885 at some point... and have never done it. Indeed a major rework and a breaking release is a way to go here. I am not sure I will have time for it tho

**Comment by timja** [comment]
Sure some of the changes are required to test it though on new core as there was a compilation failure and a couple of spotbugs issues

**Comment by fqueiruga** [comment]
Can you help me understand why the form submission fails? AFAIU there's no fundamental difference in form inputs, just layout.

**Comment by timja** [comment]
> Can you help me understand why the form submission fails? AFAIU there's no fundamental difference in form inputs, just layout.

Not sure, somewhere in the javascript, haven't looked closely but it was the exact same issue on the artifactory-plugin and matrix-auth-plugin

**Comment by fqueiruga** [comment]
I'll try to have a deeper look at it to see if there's a fix we can land on Jenkins side

**Comment by timja** [comment]
Thanks, would be great

**Comment by oleg-nenashev** [comment]
Hi! Is it still actual after the recent changes in the core?

**Comment by timja** [comment]
The fix was merged in https://github.com/jenkinsci/ownership-plugin/pull/83

**Pull request closed without merging**
