### PR TITLE
[FIXED JENKINS-28712] Do not show ownership boxes if empty

### PR DESCRIPTION
**Pull request by olivergondza**
[JENKINS-28712](https://issues.jenkins-ci.org/browse/JENKINS-28712)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Sorry for missing this PR. I've implemented a configurable approach in #42 .In particular cases I'd like to display the box with "Make me an owner" hyperlink, so I would prefer to retain the case somehow. In #42 you can disable the visualization in global options

**Comment by olivergondza** [comment]
I have suggested the 'make me an owner' button for the owernship configuration page. But anyway, this would work equally well (provided that user without necessary permission will not see an empty box).

**Comment by oleg-nenashev** [comment]
@olivergondza 
Yes, now I recall this thread. I had no time to work with plugin for a long time, but hopefully I'll add something to address this case.

**Comment by oleg-nenashev** [comment]
I suppose it can be closed in favor of #42. Thanks for the fix proposal! Hopefully I'll be able to spend more time on this plugin.

**Comment by olivergondza** [comment]
Agreed

**Pull request closed without merging**
